version: "3.9"
services:
  demo-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
      - "8501:8501"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia

